# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: teracy/angular-cli:latest
#image: teracy/angular-cli:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
#services:
#  - mongo:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache

before_script:
 - ls -l
 - cd ./server; npm install --silent --loglevel warn ; cd ..
 - cd ./front; npm install --silent  --loglevel warn ; cd ..
 - cd ./angular-src; npm install --silent  --loglevel warn ; cd ..

stages:
  - build
  - test
  - deploy


cache:
  paths:
  - node_modules/


lint_backend:
  stage: build
  environment: dev
  script:
    - cd ./server; npm run lint
    
lint_angular:
  stage: build
  environment: dev
  script:
    - cd ./angular-src; ng lint

lint_frontend:
  stage: build
  environment: dev
  script:
    - cd ./front; npm run lint
    - echo lint



#test_front:
#  stage: build
#  environment: qa
#  script:
#    - cd ./front; npm test
#    - cd ./front; ./node_modules/@angular/cli/bin/ng build


test_middle:
  stage: test
  environment: qa
  script:
#  - cd ./server;npm test
  - echo test
